version: "3.3"
services:
  app: 
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_LINK: jdbc:postgresql://postgres:5432/challenge_mp
      DB_USER: postgres
      DB_PASSWORD: 123456
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: challenge_mp
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
